language: cpp
sudo: false

matrix:
  include:
    - os: linux

install:
  # apt LLVM does not have RTTI enabled, but conda's does:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --prepend channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cmake llvmdev clangdev bdw-gc

before_script:
  - export CXX=clang
  - ${CXX} --version
  - llvm-config --version
  - llvm-config --prefix

  - cd ${TRAVIS_BUILD_DIR}
  - (cd build && cmake -DLLVM_DIR=`llvm-config --cmakedir` ..)

script:
  - cmake --build build

notifications:
  email: false
