language: cpp
sudo: false

matrix:
  include:
    - os: linux

install:
  # apt's LLVM does not have RTTI enabled, but conda's does:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge cmake llvmdev clangdev bdw-gc

before_script:
  - export CXX=clang
  - ${CXX} --version
  - llvm-config --version
  - llvm-config --prefix
  - llvm-config --has-rtti

script:
  - (cd build && cmake -DCMAKE_EXE_LINKER_FLAGS="-lstdc++ -rdynamic" -DLLVM_DIR=`llvm-config --cmakedir` ..)
  - cmake --build build

notifications:
  email: false
