language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - LLVM_VERSION=6.0.1
        - CONDA_OS_NAME=Linux
        - OCAML_VERSION=4.07

    - os: osx
      env:
        - LLVM_VERSION=6.0.1
        - CONDA_OS_NAME=MacOSX
        - OCAML_VERSION=4.07

addons:
  apt:
    packages:
      - libzmq3-dev
      - libgc-dev
  homebrew:
    packages:
      - zmq
      - libgc

install:
  # install OCaml:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - opam update
  - opam install -y ocamlfind core core_extended core_bench dune ctypes ctypes-foreign ANSITerminal menhir ppx_deriving zmq nocrypto yojson cstruct hex
  - eval $(opam env)

  # apt's LLVM does not have RTTI enabled, but conda's does:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-${CONDA_OS_NAME}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge cmake llvmdev=${LLVM_VERSION} clangdev=${LLVM_VERSION}
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CC=clang CXX=clang++; fi

before_script:
  - ${CXX} --version
  - llvm-config --version
  - llvm-config --prefix
  - llvm-config --has-rtti
  - export LLVM_DIR=`llvm-config --cmakedir`
  - export SEQ_PATH="${TRAVIS_BUILD_DIR}/stdlib"

script:
  - mkdir build
  - (cd build && cmake ..)
  - cmake --build build
  - build/seqtest
  - build/seq test/core/helloworld.seq

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bcb19a2bb1bab2a3b1b
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
