language: cpp
sudo: false

matrix:
  include:
    - os: linux
      env: LLVM_VERSION=6.0.0
      addons: { apt: { packages: ["clang-6.0"], sources: ["llvm-toolchain-trusty-6.0", "ubuntu-toolchain-r-test"] } }

before_install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - export PATH="$HOME/.linuxbrew/bin:$PATH"

install:
  - if [[ "${LLVM_VERSION}" != "" ]]; then export CXX="clang++-${LLVM_VERSION%.[0-9]}"; fi
  - ${CXX} --version

  - brew install cmake || brew upgrade cmake
  - cmake --version

  - brew install --with-toolchain llvm || brew upgrade llvm

  - brew install bdw-gc || brew upgrade bdw-gc

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (cd build && cmake .. -DLLVM_DIR=`brew --prefix llvm`/lib/cmake/llvm)

script:
  - cmake --build build

notifications:
  email: false
