language: cpp
sudo: required

matrix:
  include:
    - os: linux
    - os: osx

addons:
  apt:
    update: true
    packages:
      - libsnappy-dev
      - binutils-dev
      - libomp-dev
      - texinfo
      - python3
      - python3-pip
      - python3-setuptools
      - doxygen
  homebrew:
    update: true
    packages:
      - snappy
      - binutils
      - libomp
      - texinfo
      - python3
      - doxygen
      - cmake

before_install:
  # build and cache LLVM/Tapir:
  - |
    if [[ -z "$(ls -A ${TRAVIS_BUILD_DIR}/Tapir-LLVM)" ]]; then
      git clone -b release_60-release https://github.com/wsmoses/Tapir-LLVM ${TRAVIS_BUILD_DIR}/Tapir-LLVM
      mkdir ${TRAVIS_BUILD_DIR}/Tapir-LLVM/build
      cd ${TRAVIS_BUILD_DIR}/Tapir-LLVM/build
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export LLVM_BINUTILS_INCDIR=/usr/include
      elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export LLVM_BINUTILS_INCDIR=/usr/local/opt/binutils/include
      fi
      cmake .. -DLLVM_INCLUDE_TESTS=OFF \
               -DLLVM_ENABLE_RTTI=ON \
               -DCMAKE_BUILD_TYPE=Release \
               -DLLVM_TARGETS_TO_BUILD=host
      cmake --build .
      cd -
    fi

  # install OCaml:
  - export OCAML_VERSION=4.07
  - |
    if [[ -z "$(ls -A ${HOME}/.opam)" ]]; then
      wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
      bash -ex .travis-ocaml.sh
      opam update
      opam install -y ocamlfind core dune ctypes ctypes-foreign menhir ppx_deriving
      sudo cp /usr/local/bin/opam ${HOME}/.opam/
    else
      sudo cp ${HOME}/.opam/opam /usr/local/bin/
    fi
  - eval $(opam env)

install:
  # install libffi:
  - wget -c https://github.com/libffi/libffi/archive/v3.2.1.tar.gz -O - | tar -xz
  - cd libffi-3.2.1
  - ./autogen.sh
  - ./configure CFLAGS="-fPIC" --enable-portable-binary --enable-static --disable-shared
  - make LDFLAGS="-static"
  - sudo make install
  - cd -

  # install Boehm GC:
  - git clone -b release-7_6 https://github.com/ivmai/bdwgc
  - cd bdwgc
  - git clone -b release-7_6 https://github.com/ivmai/libatomic_ops
  - ./autogen.sh
  - |
    ./configure CFLAGS="-fPIC" --enable-threads=posix \
                               --enable-cplusplus \
                               --enable-thread-local-alloc \
                               --enable-large-config
  - make LDFLAGS="-static"
  - make check
  - sudo make install
  - cd -

  # install htslib:
  - wget -c https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 -O - | tar -xj
  - cd htslib-1.9
  - ./configure CFLAGS="-fPIC"
  - make
  - sudo make install
  - cd -

  # install dependencies for docs:
  - pip3 install --upgrade --user pip
  - pip3 install --user wheel sphinx sphinx-rtd-theme breathe exhale

before_script:
  - export SEQ_PATH="${TRAVIS_BUILD_DIR}/stdlib"
  - export PYTHONPATH="${TRAVIS_BUILD_DIR}/test/python"
  - export LDFLAGS="-L/usr/local/lib"
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo ldconfig; fi

script:
  - mkdir build
  - |
    (cd build && cmake .. -DSEQ_THREADED=ON \
                          -DLLVM_DIR=`${TRAVIS_BUILD_DIR}/Tapir-LLVM/build/bin/llvm-config --cmakedir` \
                          -DCMAKE_C_COMPILER=clang \
                          -DCMAKE_CXX_COMPILER=clang++)
  - cmake --build build
  - build/seqtest 2> /dev/null
  - build/seqc test/core/helloworld.seq
  - (cd docs/sphinx && make html 2> /dev/null)

before_deploy:
  - export SEQ_BUILD_ARCHIVE=seq-`uname | awk '{print tolower($0)}'`.tar.gz
  - tar -czf ${SEQ_BUILD_ARCHIVE} build

deploy:
  provider: releases
  api_key:
    secure: k/c1kq5t4gL32Mdl4UJFFQYFGiEV2TyOuhTdALJtnhLBuGgYHQaybnk7zF4Nf123se6bc2r4byfyNh9CiOtcrT6Cp0MUw63p+dh6MfQdWlhIDH8c33oDerpBJwNBIJ3FXb3DCW394uXfTMni6+yT1Jfhhg2j7+RyHvi1yhsMB0Lu3Mdw3YlaYTDg8X8jYo0bfJ2RWmXZ6OkwtUlTdN+JHu6WF4YNIdcX9EpBmGgi8lEtvbs4fuALQWcJG9TapbGoAq++87oh6MlGBUZDP05aVv0JAh+NMO0iyzxt+1PZuCrE1/Y3tuhXJngr5M6+6XOt9rtPhxh50q2Jd6N0zCjpj9EcXbS99DGcPWrLjzT7yM8Yim/2cUoEeYWeRD3+lGG4+rcCnkbRK3HPAxbrzefpPvrPuVYN3QuO3ypHOoWy7SOMClJBwAaIk/1diy2mWAOcus+JVKL58mCo5QcqmbFX320pALDFC/8XMMSg0+82wxlVttaZUv3j3OcCX0fUSb4PLhuakxsysdyJ8T9FCBssjnwco4Kgae1LOL/CPy7bTjtH9vtq8aQ5k9o4ylvwAwQ2iFgX2ZATptESIuFjCYb264GtTP55bZhQkrGjYpT+BghalBiBlwqmbBaML6+vSbYZCbtnyMmJ3pCLjhkIgV8KM99FRFhrW2sTou9WqupxZJg=
  file: ${SEQ_BUILD_ARCHIVE}
  skip_cleanup: true
  on:
    repo: seq-lang/seq
    tags: true

cache:
  timeout: 1000
  directories:
    - Tapir-LLVM
    - ${HOME}/.opam

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bcb19a2bb1bab2a3b1b
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
